SC47945: Add domain tags to snowflake resources and update looker dashboard
FindHotel/snowflake-usage-block pull request #5
Opened 2022-07-26 09:31 UTC by mayconbordin

### Value of doing this
So that we can correctly report costs associated with the DWH to the domains using them.

### What needs to be done

- Update the `domain` module to;
  - Create a generic `owner` tag including as values all super domains, squads and some generic values (eg. `fh`).
  - Create a `superdomain` tag including as values all super domains and some generic values (eg. `fh`).
  - Create a `squad` tag including as values all squads and some generic values (eg. `fh`).
  - Assign the tags to warehouses and databases.
  - Keep an eye on warehouses created outside squads or domains, as these should ideally be assigned to a domain or squad and at least to a generic owner.

- Update the Snowflake usage block in Looker to use the tags:
  - Create new views for the `TAGS` and `TAG_REFERENCES` views of the Snowflake usage DB.
  - Join these views to the relevant explores.
  - Update the costs dashboard to use the tags for filtering.

### Acceptance criteria
Using the Existing Looker snowflake dashboard or a new one, I can grasp the Snowflake costs  associated to each FH domain. This includes the newly-created resources for FE/CX, OTA and CA.

2022-07-28 13:39 UTC, inigofh requested changes

2022-07-28 13:39 UTC, inigofh commented on snowflake_usage_block.model.lkml
> +  join: tag_references {
I'd suggest adding the join type:

```suggestion
  join: tag_references {
    type: left_outer
```

2022-07-28 13:39 UTC, inigofh commented on snowflake_usage_block.model.lkml
> +      AND ${query_history.schema_name} = ${tag_references.object_schema} ;;
Do we need something here like what you have on other joins?

```suggestion
    sql_on:
      ${query_history.database_name} = ${tag_references.object_database}
      AND ${query_history.schema_name} = ${tag_references.object_schema}
      AND ${tag_references.domain} = 'SCHEMA' ;;
```

2022-07-28 13:39 UTC, inigofh commented on snowflake_usage_block.model.lkml
> +    relationship: many_to_one
Probably `many_to_many`, right?

```suggestion
    relationship: many_to_many
```

2022-07-29 07:17 UTC, inigofh commented
Hey @mayconbordin, my suggestions to add the join type and to use many to many applied to all joins you created. My bad because I didn't specify it.

2022-07-29 08:03 UTC, mayconbordin commented
> Hey @mayconbordin, my suggestions to add the join type and to use many to many applied to all joins you created. My bad because I didn't specify it.

It only applied to one join:

```
join: tag_references {
    type: left_outer
    sql_on:
      ${query_history.database_name} = ${tag_references.object_database}
      AND ${query_history.schema_name} = ${tag_references.object_schema}
      AND ${tag_references.domain} = 'SCHEMA' ;;
    relationship: many_to_many
  }
```

All the other joins are many_to_one.

2022-07-29 08:16 UTC, inigofh approved these changes

2022-08-09 19:50 UTC, merged